name: Publish
on:
  push:
    branches:
      - main
jobs:
  Publish:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --allow-dirty || echo "Cargo publish failed, continuing..."
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      - name: Build
        run: cargo build --release
      - name: Get Version
        id: get_version
        run: echo "version=$(grep '^version =' Cargo.toml | cut -d' ' -f3 | tr -d '\"')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest  
          name: ${{ github.event.repository.name }} - ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/auditorium
          tag_name: latest  
          name: ${{ github.event.repository.name }} - ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
